import type { Metadata, Viewport } from "next";
import "@/styles/tokens/colors.css";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { Inter } from "next/font/google";
import "./styles.scss";
import { createClient } from "@/lib/supabase/server";

export const metadata: Metadata = {
  title: "lol note",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  themeColor: "#111",
};

const appFont = Inter({
  subsets: ["cyrillic", "latin"],
  display: "swap",
  variable: "--font-app",
});

const isAuthUser = async (): Promise<boolean> => {
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  return user ? true : false;
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isAuth = await isAuthUser();

  return (
    <html lang="ru" className={appFont.variable}>
      <body>
        <div id="modal"></div>
        <Sidebar isAuth={isAuth} />
        <main className="app-content scrollbar">{children}</main>
      </body>
    </html>
  );
}
