import type { Metadata, Viewport } from "next";
import "@/lib/assets/styles/tokens/colors.css";
import "./globals.css";
import Sidebar from "@/components/sidebar";

export const metadata: Metadata = {
  title: "lol note",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  themeColor: "#111",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body>
        <div id="modal"></div>
        <Sidebar />
        <main className="app-content">{children}</main>
      </body>
    </html>
  );
}
